### ISSUE TITLE
`--location` (follow redirects) is not necessary with `Http` client; what to do?

### ISSUE THREAD

**Issue by nexxai** [laravel-shift/curl-converter#10]
Just wondering how you want to handle the `--location` flag.  With cURL, it means "follow any redirects" but the Laravel `Http` client does this by default.  

My thinking is to just silently accept and discard it so that it doesn't throw an error like this:

<img width="753" alt="Screen Shot 2022-10-11 at 10 39 23 AM" src="https://user-images.githubusercontent.com/4316564/195150237-aba9a73b-2976-4276-88fe-2ba88e08241d.png">

Thoughts?  I'm happy to add this "feature" if you're ok with the idea of just ignoring it.

**Comment by jasonmccreary** [comment]
Sure. Could just add the option to the command and do nothing with it. 👍

**Comment by nexxai** [comment]
Yeah, that's what I was going to do.  Will send a PR shortly.  Thanks JMac :)

**Comment by jasonmccreary** [comment]
@nexxai, awesome! Throw in a quick test if you don't mind. Just to demonstrate it does nothing.

**Comment by nexxai** [comment]
Consider it done.
