### ISSUE TITLE
`--data-raw` not supported

### ISSUE THREAD

**Issue by atymic** [laravel-shift/curl-converter#8]
Many tools such as postman use `data-raw`. Maybe worth adding support for this, esp for json requests?

```
curl --request POST 'https://api.com' \
--header 'Accept: application/json' \
--header 'Content-Type: application/json' \
--data-raw '{
    "messages": [
        "a",
        "b",
        "c"
    ]
}'
```

**Comment by jasonmccreary** [comment]
Good one. I'll get this added in the coming weeks. However, it shouldn't be too hard to implement if you (or another reader) wants to submit a PR.

**Comment by jasonmccreary** [comment]
Initial support was added in #15. We'll see how it goes.
