### ISSUE TITLE
php curl support

### ISSUE THREAD

**Issue by chadleverington** [laravel-shift/curl-converter#9]
Would be great if it could also support for php curl to Http facade. e.g.

$ch = curl_init();
curl_setopt($ch, CURLOPT_URL, 'https://www.example.com/includes/api.php');
curl_setopt($ch, CURLOPT_POST, 1);
curl_setopt($ch, CURLOPT_POSTFIELDS,
    http_build_query(
        array(
            'action' => 'GetProducts',
            // See https://developers.whmcs.com/api/authentication
            'username' => 'IDENTIFIER_OR_ADMIN_USERNAME',
            'password' => 'SECRET_OR_HASHED_PASSWORD',
            'pid' => '1',
            'responsetype' => 'json',
        )
    )
);
curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
$response = curl_exec($ch);
curl_close($ch);

becomes

$result = Http::asForm()->post('https://www.example.com/includes/api.php', [
                        'action' => 'GetProducts',
                        'username' => 'IDENTIFIER_OR_ADMIN_USERNAME',
                        'password' => 'SECRET_OR_HASHED_PASSWORD',
                        'pid' => '1',
                        'responsetype' => 'json',
])->json();

**Comment by jasonmccreary** [comment]
That's be cool. Probably not something I'll add to this project. Maybe a task in the [Shift Workbench](https://laravelshift.com/workbench) though.

**Comment by verhovsky** [comment]
@chadleverington https://curlconverter.com/php/
